version: "3"
services:
  nodejs:
    networks:
      - todomysql
    build: .
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=mysql-service.default.svc.cluster.local
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_DATABASE=todo_list
    depends_on:
      - mysql

  mysql:
    networks:
      - todomysql
    image: mysql:latest
    environment:
      - MYSQL_USER=todouser  
      - MYSQL_PASSWORD=todopass
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todo_list
  
networks:
  todomysql:
    driver: bridge
